### ISSUE TITLE
Search nothing returns every blog

### ISSUE THREAD

**Issue by pattarinn** [NarawishS/ku-hub#64]
When I click on go! button without typing anything in search box, it returns every blog in the program with the sentence ```Searching with keyword:```
```Searching results: (number of all blogs in app)``` and then show every blog in the app.

I'm not sure if you determine to do this, but changing words might be a great idea.

**Comment by keyboard2543** [comment]
@pattarinn:
> When I click on go! button without typing anything in search box, it returns every blog in the program with the sentence `Searching with keyword:`
> `Searching results: (number of all blogs in app)` and then show every blog in the app.
> 
> I'm not sure if you determine to do this, but changing words might be a great idea.


Yes, It is a feature. This would search the exactly for **the string** of the keyword.
And because all blogs are contain a blank string `""` then it will search for all blogs that related with a string `""`

A keyword can be used to search for: 
- Blog author
- Blog title
- Blog description
- Blog tags

Thanks for the issue.
